User
name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to S3
        run: |
          aws configure set aws_access_key_id ${{ASIAXPLL76VMUIYJS2IC}}
          aws configure set aws_secret_access_key ${{YMXkr0gqIkevtBjwJOmmclVGvcfb3xJXTBcieNDX}}
          aws s3 sync ./build s3://chat-anwendung--bucket


    

